name: Deploy Redirects

on:
  push:
    branches: ["main"]
  workflow_dispatch: # 手動実行もできるようにしておく

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Generate Redirects
        run: python generate.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # 生成されたファイルがあるディレクトリ（カレントなら . ）
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
